apiVersion: v1
kind: Service
metadata:
  name: cicd-springboot-service
spec:
  type: LoadBalancer
  selector:
    app: cicd-springboot
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8081
